LDFLAGS := $(LDFLAGS) -lm -lrlutils -lrlenvironment -lrlgluenetdev
CFLAGS := $(CFLAGS) -Wall -pedantic -g  #?
CC := $(CXX)

all: tictactoe bandits mines

## bandits
bandits:     environments/bandits/BanditEnvironment.o 
	$(CC)    environments/bandits/BanditEnvironment.o $(LDFLAGS) -o environments/bandits/BanditEnvironment  
environments/bandits/BanditEnvironment.o:   environments/bandits/BanditEnvironment.cc
	$(CC)    $(CFLAGS) -c environments/bandits/BanditEnvironment.cc -o environments/bandits/BanditEnvironment.o

## mines
mines:     environments/mines/MinesEnvironment.o 
	$(CC)    environments/mines/MinesEnvironment.o $(LDFLAGS) -o environments/mines/MinesEnvironment  
environments/mines/MinesEnvironment.o:   environments/mines/MinesEnvironment.cc
	$(CC)    $(CFLAGS) -c environments/mines/MinesEnvironment.cc -o environments/mines/MinesEnvironment.o

## tictactoe
tictactoe: environments/tictactoe/MyEnvironment.o 
	$(CC)    environments/tictactoe/MyEnvironment.o $(LDFLAGS) -o environments/tictactoe/MyEnvironment  

tictactoe.o: environments/tictactoe/MyEnvironment.cpp
	$(CC)    $(CFLAGS) -c environments/tictactoe/MyEnvironment.cpp -o environments/tictactoe/MyEnvironment.o

clean:
	rm -rf environments/bandits/BanditEnvironment environments/bandits/BanditEnvironment.exe environments/bandits/*.o
	rm -rf environments/tictactoe/MyEnvironment environments/tictactoe/MyEnvironment.exe environments/tictactoe/*.o









