LDFLAGS := $(LDFLAGS) -lm -lrlutils -lrlagent -lrlgluenetdev
CFLAGS := $(CFLAGS) -Wall -pedantic

all: LibRLAgent

LibRLAgent: agent/LibRLAgent.o 
	$(CXX)   agent/LibRLAgent.o $(LDFLAGS) -o agent/LibRLAgent

LibRLAgent.o: agent/LibRLAgent.cpp
	$(CXX)  $(CFLAGS) -c agent/LibRLAgent.cpp -o agent/LibRLAgent.o 

clean:
	rm -rf agent/LibRLAgent agent/LibRLAgent.exe *.o









