LDFLAGS := $(LDFLAGS) -lm -lrlutils -lrlagent -lrlgluenetdev
CFLAGS := $(CFLAGS) -Wall -pedantic

all: MyAgent

MyAgent: MyAgent.o 
	$(CXX)   MyAgent.o $(LDFLAGS) -o MyAgent      

MyAgent.o: MyAgent.cpp
	$(CXX)  $(CFLAGS) -c MyAgent.cpp -o MyAgent.o 

clean:
	rm -rf MyAgent MyAgent.exe *.o









